@echo off
echo Starting CardioPredict Heart Disease Assessment System...
echo.
echo Installing dependencies...
pip install -r requirements.txt
echo.
echo Starting Flask application...
python app.py
pause